<?php

class Eleve_model extends Utilisateur_model
{

    private $table = 'Eleve';

    public function __construct()
    {
        parent::__construct();
    }

    public function add(array $data): bool
    {
        parent::add($data); // TODO: Change the autogenerated stub
    }

    public function get(array $data): ?array
    {
        return $this->db->select('classe, pastille')
            ->from($this->table)
            ->get()
            ->resul_array()[0];
    }

    public function del(array $data): bool
    {
        return parent::del($data); // TODO: Change the autogenerated stub
    }

    public function set(array $data): bool
    {
        return parent::set($data); // TODO: Change the autogenerated stub
    }

    public function setPastille(string $userID, string $pastille): bool
    {
        
    }

}