<?php

class Eleve_model extends Utilisateur_model
{

    private $table = 'Eleve';


    public function __construct()
    {
        parent::__construct();
    }

    public function add(array $data): bool
    {
        parent::add($data); // TODO: Change the autogenerated stub
    }

    public function get(array $data): ?array
    {
        return $this->db->select('classe, pastille')
            ->from($this->table)
            ->get()
            ->result_array()[0];
    }

    public function del(array $data): bool
    {
        return parent::del($data); // TODO: Change the autogenerated stub
    }

    public function set(array $data): bool
    {
        return parent::set($data); // TODO: Change the autogenerated stub
    }

    public function setPastille(string $userID, string $pastille): bool
    {
        
    }

    public function getAll(): ?array
    {
        return $this->db->select()
            ->from($this->table)
            ->get()
            ->result_array();
    }

    public function getClasse(string $classID): array
    {
        return $this->db->select()
            ->from($this->table)
            ->where(array('classe'=>$classID))
            ->get()
            ->result_array();
    }

    /**
     * Return if the childList property has to been updated
     */
    private function needUpdate()
    {
        if ($this->lastModified === false){
            return false;
        }
        if (isset($this->lastUpdated)){
            return $this->lastModified > $this->lastUpdated;
        }
        return true;
    }

}